package hibernateUser;

// Generated 2014/12/2 �U�� 11:03:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "coreyou_corp")
public class User implements java.io.Serializable {

	private String userId;
	private String nickName;
	private byte[] password;
	private String userName;
	private String gender;
	private Date birthday;
	private String email;
	private String phoneNumber;
	private String address;
	private String idLastFourNum;
	private Date createTime;
	private Date activateTime;
	private String activateCode;

	public User() {
	}

	public User(String userId, Date createTime) {
		this.userId = userId;
		this.createTime = createTime;
	}

	public User(String userId, String nickName, byte[] password,
			String userName, String gender, Date birthday, String email,
			String phoneNumber, String address, String idLastFourNum,
			Date createTime, Date activateTime, String activateCode) {
		this.userId = userId;
		this.nickName = nickName;
		this.password = password;
		this.userName = userName;
		this.gender = gender;
		this.birthday = birthday;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.idLastFourNum = idLastFourNum;
		this.createTime = createTime;
		this.activateTime = activateTime;
		this.activateCode = activateCode;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false, length = 24)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "nickName", length = 36)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "password")
	public byte[] getPassword() {
		return this.password;
	}

	public void setPassword(byte[] password) {
		this.password = password;
	}

	@Column(name = "userName", length = 24)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "gender", length = 2)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phoneNumber", length = 36)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "idLastFourNum", length = 4)
	public String getIdLastFourNum() {
		return this.idLastFourNum;
	}

	public void setIdLastFourNum(String idLastFourNum) {
		this.idLastFourNum = idLastFourNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "activateTime", length = 19)
	public Date getActivateTime() {
		return this.activateTime;
	}

	public void setActivateTime(Date activateTime) {
		this.activateTime = activateTime;
	}

	@Column(name = "activateCode", length = 42)
	public String getActivateCode() {
		return this.activateCode;
	}

	public void setActivateCode(String activateCode) {
		this.activateCode = activateCode;
	}

}
